### PR TITLE
Update

### PR DESCRIPTION
**Pull request by mcremone**

### CODE REVIEW

**Comment by fdolek** [comment]
I have been waiting that changes to be merged with main repo, why it gets late ? is it about just merge conflict?

**Comment by mcremone** [comment]
> I have been waiting that changes to be merged with main repo, why it gets late ? is it about just merge conflict?

It would be good to fully test this before merging. I may actually use your help in testing the effect of the NNLO/NLO corrections you included.

**Comment by fdolek** [comment]
okay,  then I will copy your branch

**Comment by areinsvo** [comment]
A few comments after a brief look at this PR:
- [ ] Lumi for 2018, according to [the summary table](https://twiki.cern.ch/twiki/bin/viewauth/CMS/PdmVAnalysisSummaryTable) should be 59.74 instead of 59.97
- [ ] Why is BadPFMuonFilter not included for the 2018 MET filters? According to the [official recommendations](https://twiki.cern.ch/twiki/bin/view/CMS/MissingETOptionalFiltersRun2#Analysis_Recommendations_for_ana), it should be included for all 3 years.
- [ ] Why did the pt requirements change for taus and both loose and tight electrons? I'm trying to manually compare [the new version](https://github.com/mcremone/decaf/blob/master/analysis/util/ids.py) with what we had [before](https://github.com/LPC-DM/decaf/blob/04fb993c8e6902bbfb19cde0c208524c79838152/analysis/secondary_inputs/ids.py).  (FYI, there is a “git mv” command that lets you move files to a new location in the repository while maintaining the full git history. That makes it a lot easier to see what has changed.)

@Quantumapple can you post the link to the most recent set of plots here?

@mcremone can you resolve the merge conflicts in analysis/run.sh?

**Comment by mcremone** [comment]
@areinsvo Thanks for catching the wrong lumi and the missing MET filter. Regarding the different IDs, they have been updated to be in sync with mono-jet, when possible.

**Comment by Quantumapple** [comment]
@areinsvo This is the most recent set of plots I made.

[March29v2.pdf](https://github.com/LPC-DM/decaf/files/4412040/March29v2.pdf)

**Pull request merged**
