### PR TITLE
Unified analysis thres., IDs

### PR DESCRIPTION
**Pull request by trtomei**
Single file for unified analysis thresholds and IDs.
FIXME: we don't have the branch "Tau_idMVAoldDM2017v2" in our nanoAODs, that should be the Tau ID we are cutting in... 
https://twiki.cern.ch/twiki/bin/view/CMS/TauIDRecommendation13TeV#2017v2_discriminators

I put "Tau_idAntiEle" for the time being, but we should address this later... :(

### CODE REVIEW

**Comment by mcremone** [comment]
Also, I would make a difference between cuts for object ID and analysis cuts.

The definition of loose/tight muons/electrons/taus/photons is somehow centralized, but the definition of good/clean jets is specific for this analysis, all the thresholds should go in the main analysis code. This is especially true for analysis cuts like the minDPhi.

**Comment by mcremone** [comment]
Following your ideas and the output of this discussion, I put together this:

https://github.com/LPC-DM/decaf/blob/master/grinder/analysis/ids.py

is tested in my last commit and it's working.

**Comment by mcremone** [comment]
Actually I moved everything in a utils folder:

https://github.com/LPC-DM/decaf/tree/master/grinder/utils

**Comment by trtomei** [comment]
I close this PR in view of the reorganisation of the code.

**Pull request closed without merging**
